import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container mx-auto py-2 px-4">
          <Header />
          {children}
          <footer className="text-center text-gray-600 py-8">
            Job Board &copy; 2024 - All rights reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
